---
title: "Project Milestone 3"
author: "Group3: Evelyn Tollar, Emma Chen, Andrea Chen, Maya Barron, Jinwen Xu"
date: "2023-05-02"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
knitr::opts_chunk$set(warnings = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(stringr)
library(ggplot2)
library(scales)
library(patchwork)
mortality <- read.csv("https://github.com/AndreaChen0301/stat436/raw/main/mortality_ph2.5.csv")%>%
  rename_at(vars(starts_with('X')), funs(sub("X", " ", .))) %>% 
  pivot_longer(!Country, names_to = "Year", values_to = "prematured_death")

welfare.percent <- read.csv("https://github.com/AndreaChen0301/stat436/raw/main/percent_welfare.csv")%>%
  rename_at(vars(starts_with('X')), funs(sub("X", " ", .))) %>% 
  pivot_longer(!Country, names_to = "Year", values_to = "cost_percent")

mortality_per <- read.csv("https://github.com/AndreaChen0301/stat436/raw/main/mortality_per_mili.csv") %>%
  rename_at(vars(starts_with('X')), funs(sub("X", "", .))) %>% 
  pivot_longer(!Country, names_to = "Year", values_to = "death_per_million")

mortality_per$Country[mortality_per$Country=="T\x9frkiye"]="Türkiye"
```

```{r}
health = right_join(welfare.percent, mortality, c("Country", "Year")) %>%
  mutate(Year=as.numeric(Year))
health2 = right_join(welfare.percent, mortality_per, c("Country", "Year")) %>%
  mutate(Year = as.numeric(Year))

complete.country = read.csv("https://github.com/AndreaChen0301/stat436/raw/main/co_emmit.csv") %>%
  group_by(Country) %>%
  mutate(nyear = n()) %>%
  filter(nyear==31) %>%
  pull(Country) %>%
  unique()

mortality = health %>%
  filter(Country %in% complete.country) %>%
  mutate(Year = as.character(Year)) %>%
  filter(Year == "1990" | Year == "2019")%>%
  filter(Country !="Russia")

mortality2 = health2 %>%
  filter(Country %in% complete.country) %>%
  mutate(Year = as.character(Year)) %>%
  filter(Year == "1990"| Year == "2019")

top.10 = mortality %>%
  group_by(Country) %>%
  summarise(death = mean(prematured_death))%>%
  arrange(desc(death))%>%
  slice_head(n=10)%>%
  pull(Country)
```

```{r}
mortality %>%
  filter(Country %in% top.10) %>%
  ggplot(aes(x=reorder(Country, prematured_death), y=prematured_death, fill = Year))+
  geom_col(position="dodge", stat = "identity", width=0.7)+
  scale_fill_manual(values=c("#D95F02", "#1B9E77"))+
  geom_text(aes(label=prematured_death), position=position_dodge(width=0.75), vjust=-0.75, size=3)+
  labs(x="Country", y="Number of Premature Death", title = "Top 10 Country with Most Premature Death Caused by Ambient Particulate Matter (PM) in 1990 and 2019")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size=15),
        axis.ticks = element_blank(),
        panel.grid.major.x = element_blank())
```

```{r}
mortality2 %>%
  filter(Country %in% top.10) %>%
  ggplot(aes(x=reorder(Country, death_per_million), y=death_per_million, fill = Year))+
  scale_fill_manual(values=c("#D95F02", "#1B9E77"))+
  geom_col(position="dodge", width=0.7)+
  geom_text(aes(label=death_per_million), position=position_dodge(width=0.75), hjust=0.4, vjust=-0.65, size=3)+
  scale_y_continuous(expand = c(0, 0, 0.1, 0.1))+
  labs(x="Country", y="Premature Death per Million", title = "Top 10 Countries with Most Premature Death Inhabitant Caused by PM in 1990 and 2019")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size=15),
        axis.ticks = element_blank(),
        panel.grid.major.x = element_blank())
```
